# Generated by Django 5.0.2 on 2024-04-11 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
